`timescale 1ns / 1ps

// The PL payload for both boards: a counter blinking LEDs off the
// PS-provided fabric clock, held in reset until the PS releases the PL.
// Deliberately tiny - the entire point of module 13 is where the clock
// comes FROM, not what runs on it.
module ps_blinky_core (
    input        pl_clk,     // 100MHz, generated by the PS
    input        pl_resetn,  // released by the PS after boot/config
    output [3:0] led
);

    reg [26:0] counter = 0;
    always @(posedge pl_clk) begin
        if (!pl_resetn) counter <= 0;
        else            counter <= counter + 1'b1;
    end

    assign led = counter[26:23];   // ~0.75Hz to ~6Hz blink spread

endmodule
