## The RFSoC4x2's first clocked-design constraints file - and it contains
## no clock. pl_clk0 is generated by the PS and constrained automatically;
## only the PL LEDs need pins, verbatim from
## boards/rfsoc4x2/xdc/4x2_LED_PB__SW.xdc (W_LED_0..3).
set_property PACKAGE_PIN AR11 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property PACKAGE_PIN AW10 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property PACKAGE_PIN AT11 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property PACKAGE_PIN AU10 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]

set_false_path -to [get_ports {led[*]}]

## Board-wide recommended config, per the vendored constraint file.
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
