`timescale 1ns / 1ps

// First *clocked* testbench in the repo. New machinery versus the module
// 01/02 benches: a free-running clock generated by an `always #5` block,
// stimulus applied on the opposite edge (negedge) so it's stable well
// before the flops sample it, and checks that compare state *after* an
// edge rather than instantly.
module tb_dff_variants;

    reg clk = 0, rst, en, d;
    wire q_async, q_sync, q_en;
    integer errors = 0;

    always #5 clk = ~clk;   // 100MHz-ish; period 10ns

    dff_async_reset u_async (.clk(clk), .rst(rst), .d(d), .q(q_async));
    dff_sync_reset  u_sync  (.clk(clk), .rst(rst), .d(d), .q(q_sync));
    dff_en          u_en    (.clk(clk), .rst(rst), .en(en), .d(d), .q(q_en));

    task check_q(input exp_async, input exp_sync, input exp_en, input [127:0] label);
        begin
            if (q_async !== exp_async) begin errors = errors + 1; $display("FAIL %0s: q_async=%b exp=%b", label, q_async, exp_async); end
            if (q_sync  !== exp_sync)  begin errors = errors + 1; $display("FAIL %0s: q_sync=%b exp=%b",  label, q_sync,  exp_sync);  end
            if (q_en    !== exp_en)    begin errors = errors + 1; $display("FAIL %0s: q_en=%b exp=%b",    label, q_en,    exp_en);    end
        end
    endtask

    initial begin
        // Reset everything through one clock edge so all three start known.
        rst = 1; en = 0; d = 0;
        @(negedge clk);
        @(negedge clk);
        check_q(0, 0, 0, "after reset");

        // Release reset, drive d=1: all should capture at the next edge
        // (en=1 for the enabled flop).
        rst = 0; en = 1; d = 1;
        @(negedge clk);
        check_q(1, 1, 1, "capture d=1");

        // Drop enable, change d: only q_en should HOLD its old value.
        en = 0; d = 0;
        @(negedge clk);
        check_q(0, 0, 1, "en=0 holds");

        // The async-vs-sync difference: assert rst mid-cycle, away from any
        // clock edge. The async flop resets immediately; the sync flop
        // doesn't budge until the next edge.
        en = 1; d = 1;
        @(negedge clk);
        check_q(1, 1, 1, "recapture d=1");
        #2 rst = 1;      // mid-cycle, no clock edge yet
        #1;
        check_q(0, 1, 1, "async resets immediately, sync waits");
        @(negedge clk);  // now an edge has passed
        check_q(0, 0, 0, "sync reset takes effect at edge");

        if (errors == 0) $display("PASS: tb_dff_variants - all checks correct");
        else              $display("FAIL: tb_dff_variants - %0d error(s)", errors);
        $finish;
    end

endmodule
