## Pins verbatim from boards/nexys4/xdc/Nexys4-Master.xdc: clock E3,
## CPU_RESET C12, USB-UART C4/D4, switches, LEDs (original Nexys4).
set_property PACKAGE_PIN E3 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports clk100]
create_clock -period 10.000 -name sys_clk [get_ports clk100]

set_property PACKAGE_PIN C12 [get_ports cpu_resetn]
set_property IOSTANDARD LVCMOS33 [get_ports cpu_resetn]

## USB-UART: host->FPGA on C4 (UART_TXD_IN), FPGA->host on D4
set_property PACKAGE_PIN C4 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN D4 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

## Switches
set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
set_property PACKAGE_PIN U8 [get_ports {sw[1]}]
set_property PACKAGE_PIN R7 [get_ports {sw[2]}]
set_property PACKAGE_PIN R6 [get_ports {sw[3]}]
set_property PACKAGE_PIN R5 [get_ports {sw[4]}]
set_property PACKAGE_PIN V7 [get_ports {sw[5]}]
set_property PACKAGE_PIN V6 [get_ports {sw[6]}]
set_property PACKAGE_PIN V5 [get_ports {sw[7]}]
set_property PACKAGE_PIN U4 [get_ports {sw[8]}]
set_property PACKAGE_PIN V2 [get_ports {sw[9]}]
set_property PACKAGE_PIN U2 [get_ports {sw[10]}]
set_property PACKAGE_PIN T3 [get_ports {sw[11]}]
set_property PACKAGE_PIN T1 [get_ports {sw[12]}]
set_property PACKAGE_PIN R3 [get_ports {sw[13]}]
set_property PACKAGE_PIN P3 [get_ports {sw[14]}]
set_property PACKAGE_PIN P4 [get_ports {sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

## LEDs
set_property PACKAGE_PIN T8 [get_ports {led[0]}]
set_property PACKAGE_PIN V9 [get_ports {led[1]}]
set_property PACKAGE_PIN R8 [get_ports {led[2]}]
set_property PACKAGE_PIN T6 [get_ports {led[3]}]
set_property PACKAGE_PIN T5 [get_ports {led[4]}]
set_property PACKAGE_PIN T4 [get_ports {led[5]}]
set_property PACKAGE_PIN U7 [get_ports {led[6]}]
set_property PACKAGE_PIN U6 [get_ports {led[7]}]
set_property PACKAGE_PIN V4 [get_ports {led[8]}]
set_property PACKAGE_PIN U3 [get_ports {led[9]}]
set_property PACKAGE_PIN V1 [get_ports {led[10]}]
set_property PACKAGE_PIN R1 [get_ports {led[11]}]
set_property PACKAGE_PIN P5 [get_ports {led[12]}]
set_property PACKAGE_PIN U1 [get_ports {led[13]}]
set_property PACKAGE_PIN R2 [get_ports {led[14]}]
set_property PACKAGE_PIN P2 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

set_false_path -to [get_ports {led[*]}]
set_false_path -from [get_ports {sw[*]}]
set_false_path -from [get_ports cpu_resetn]
set_false_path -to [get_ports uart_txd]
set_false_path -from [get_ports uart_rxd]

set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
