#!/usr/bin/env python3
"""Generate the sine/cosine ROM header for module 24's HLS DDS kernel.

Usage: scripts/gen_dds_tables.py OUT.h [N] [AMP]

N-entry (default 1024) int16 cos/sin tables at amplitude AMP (default
13107 = 0.4 of full scale - headroom for the DAC fine mixer).
"""
import math
import sys
from pathlib import Path

def main():
    out = Path(sys.argv[1])
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 1024
    amp = int(sys.argv[3]) if len(sys.argv) > 3 else 13107

    lines = [
        "/* GENERATED by scripts/gen_dds_tables.py - DO NOT HAND-EDIT.",
        f" * {n}-entry int16 cos/sin, amplitude {amp} (0.4 FS). */",
        "#ifndef DDS_TAB_H",
        "#define DDS_TAB_H",
        "",
        f"#define DDS_TAB_LOG2 {n.bit_length() - 1}",
        "",
    ]
    for name, fn in (("DDS_COS", math.cos), ("DDS_SIN", math.sin)):
        vals = [round(amp * fn(2 * math.pi * i / n)) for i in range(n)]
        lines.append(f"static const short {name}[{n}] = {{")
        for i in range(0, n, 12):
            lines.append("    " + ", ".join(f"{v:6d}" for v in vals[i:i + 12]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("#endif /* DDS_TAB_H */")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({n} entries, amp {amp})")

if __name__ == "__main__":
    main()
