#!/usr/bin/env python3
"""Convert TI TICS Pro register exports into a C header.

Usage:
    scripts/tics_to_header.py OUT.h NAME=FILE.txt [NAME=FILE.txt ...]

Each input file is the vendored TICS format used by PYNQ's xrfclk package
(one register per line: "Rnn<tab>0xHHHHHH"); each becomes
    static const uint32_t NAME[] = { ... };
in file order - the ORDER IS THE PROGRAMMING PROTOCOL (LMK: write top to
bottom; LMX: file lists R112..R0, written top to bottom after the reset
dance - see boards/rfsoc4x2/rfclk/UPSTREAM-README.md).
"""
import re
import sys
from pathlib import Path

def parse(path):
    vals = []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        m = re.search(r"(0x[0-9A-Fa-f]+)\s*$", line)
        if not m:
            sys.exit(f"unparseable TICS line in {path}: {line!r}")
        vals.append(int(m.group(1), 16))
    return vals

def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    out = Path(sys.argv[1])
    chunks = [
        "/* GENERATED by scripts/tics_to_header.py - DO NOT HAND-EDIT.",
        " * Source register dumps: boards/rfsoc4x2/rfclk/ (vendored verbatim",
        " * from https://github.com/Xilinx/RFSoC-PYNQ, see UPSTREAM-README.md",
        " * there for provenance and the per-chip programming protocol).",
        " */",
        "#ifndef RFCLK_REGS_H",
        "#define RFCLK_REGS_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for arg in sys.argv[2:]:
        name, _, path = arg.partition("=")
        vals = parse(path)
        chunks.append(f"/* {Path(path).name}: {len(vals)} writes, file order */")
        chunks.append(f"static const uint32_t {name}[{len(vals)}] = {{")
        for i in range(0, len(vals), 6):
            row = ", ".join(f"0x{v:06X}" for v in vals[i:i + 6])
            chunks.append(f"    {row},")
        chunks.append("};")
        chunks.append("")
    chunks.append("#endif /* RFCLK_REGS_H */")
    out.write_text("\n".join(chunks) + "\n")
    print(f"wrote {out}")

if __name__ == "__main__":
    main()
